### ISSUE TITLE
Interface module

### ISSUE THREAD

**Issue by bakermanus** [TMakins/CDH_I2C_Interface#1]
Hi,
I'm wondering if you still have interface module available?
Thanks

**Comment by knockoutperformance** [comment]
Sweet work on the heater!
Do you have an interface module available also?
Thank you for your time.

**Comment by irdispsyhonikum** [comment]
hello.

Can I also get one, please?
Great job.

Kind regards

**Comment by TMakins** [comment]
I've updated the readme and added eBay links to purchase the modules. Note these aren't programmed as I just don't have the time, but should be simple enough to program with an Arduino acting as a UPDI programmer.
