### ISSUE TITLE
cannoct make it work.

### ISSUE THREAD

**Issue by irdispsyhonikum** [TMakins/CDH_I2C_Interface#2]
Hello.

I bought your module and connected it to esp32-e. But it don't working. Remote control showing arrows behind pipe picture. To be honest not shore whe the problem is. Can you please help me to find the solution and fix this?

Kind regards
Irdis

P.S. Esp show's the screen, but data not get updatad, and pressing on stop area, only gets boarder yellow for few secconds. both lights are lighting.

**Comment by TMakins** [comment]
First thing to check is if you have comms with the interface board itself, I would suggest writing some code that just sets up I2C and reads the version reg (addr 34). If that works, we can move onto the heater comms side.

**Comment by irdispsyhonikum** [comment]
Helo.

Sorry to did not reply strait away. Yes, I was thinking to scheck same way. will check it 2mo morning after work. But before may I ask another one quastion. Do I have to place middle jumpers? I do not understand for what they are. 3v3 pover exist on the pin.

**Comment by irdispsyhonikum** [comment]
Hello TMakins,

I checked if esp32 board seas any information from your controller, and unswer is yes. So can be problemm esewhere. 

Kind regards
Irdis

**Comment by irdispsyhonikum** [comment]
And sorry, but I should as again about the jumpers with voltage on the middle. The information on the board and Yours picture voltage little bit comfusig me.

**Comment by irdispsyhonikum** [comment]
I think I've sorted. I placed Jumpers wrongly as on the picture for (3v3 picture, 5v board), and when tested output voltege wa 4.1. then I changed jumper to (3v3 board, 5v picture), then everithing get's on place. Sorry for opening case. Should ment it first.

**Comment by TMakins** [comment]
No problem, thanks for pointing out the mistake in the pinout. I've now fixed that.
